name: /Users/lucamasserano/Desktop/uni/cmu/ada/ada_code/hep-lfi
channels:
  - conda-forge
  - defaults
dependencies:
  - afterimage=1.21
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - atk=2.36.0
  - atk-1.0=2.36.0
  - attrs=20.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - c-compiler=1.1.3
  - ca-certificates=2021.1.19
  - cairo=1.16.0
  - cctools=949.0.1
  - cctools_osx-64=949.0.1
  - certifi=2020.12.5
  - cffi=1.14.4
  - cfitsio=3.470
  - clang=11.0.0
  - clang_osx-64=11.0.0
  - clangxx=11.0.0
  - clangxx_osx-64=11.0.0
  - compiler-rt=11.0.0
  - compiler-rt_osx-64=11.0.0
  - compilers=1.1.3
  - cxx-compiler=1.1.3
  - davix=0.7.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fftw=3.3.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fortran-compiler=1.1.3
  - freetype=2.10.4
  - fribidi=1.0.10
  - ftgl=2.4.0
  - gdk-pixbuf=2.42.2
  - gettext=0.19.8.1
  - gfortran_impl_osx-64=9.3.0
  - gfortran_osx-64=9.3.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.66.3
  - gmp=6.2.1
  - gobject-introspection=1.66.1
  - graphite2=1.3.13
  - graphviz=2.42.3
  - gsl=2.6
  - gtk2=2.24.32
  - gts=0.7.6
  - harfbuzz=2.7.2
  - icu=67.1
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - ipykernel=5.4.2
  - ipyparallel=6.3.0
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - isl=0.22.1
  - jinja2=2.11.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - krb5=1.17.2
  - ld64=530
  - ld64_osx-64=530
  - ldid=2.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp11=11.0.0
  - libcurl=7.71.1
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.3
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.0.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - librsvg=2.50.2
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp=1.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-openmp=11.0.0
  - llvm-tools=11.0.0
  - llvmlite=0.35.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - metakernel=0.27.5
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.2.0
  - numba=0.52.0
  - numpy=1.19.5
  - openssl=1.1.1i
  - packaging=20.8
  - pandoc=2.11.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.8.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.3.3
  - pixman=0.40.0
  - portalocker=1.7.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.10
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.7.3
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pythia8=8.244
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pyzmq=21.0.0
  - readline=8.0
  - root=6.22.6
  - root-binaries=6.22.6
  - root-dependencies=6.22.6
  - root_base=6.22.6
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.34.0
  - tapi=1100.0.11
  - tbb=2020.2
  - tbb-devel=2020.2
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - vdt=0.4.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xrootd=5.0.3
  - xxhash=0.8.0
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
    - alabaster==0.7.12
    - anyio==2.0.2
    - astroid==2.4.2
    - awkward==1.0.2
    - awkward0==0.15.2
    - babel==2.9.0
    - cachetools==4.2.0
    - chardet==4.0.0
    - click==7.1.2
    - cycler==0.10.0
    - cython==0.29.22
    - docutils==0.16
    - fastcore==1.3.18
    - fastkde==1.0.19
    - fastprogress==0.1.21
    - h5py==3.1.0
    - idna==2.10
    - imagesize==1.2.0
    - ipywidgets==7.6.3
    - isort==5.7.0
    - jedi==0.18.0
    - joblib==1.0.0
    - json5==0.9.5
    - jupyter==1.0.0
    - jupyter-console==6.2.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyter-server==1.2.2
    - jupyterlab==3.0.5
    - jupyterlab-server==2.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - lazy-object-proxy==1.4.3
    - lightgbm==3.1.1
    - lxml==4.6.2
    - matplotlib==3.2.2
    - mccabe==0.6.1
    - mpmath==1.1.0
    - nbclassic==0.2.6
    - numpydoc==1.1.0
    - pandas==1.2.0
    - patsy==0.5.1
    - pdpbox==0.2.0
    - prettytable==2.0.0
    - psutil==5.8.0
    - pylint==2.6.0
    - pytz==2020.5
    - pyyaml==5.3.1
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - requests==2.25.1
    - rfpimp==1.3.6
    - scikit-garden==0.1.3
    - scikit-learn==0.24.0
    - scipy==1.6.0
    - seaborn==0.11.1
    - sniffio==1.2.0
    - snowballstemmer==2.0.0
    - sparse==0.11.2
    - sphinx==3.4.3
    - sphinx-rtd-theme==0.5.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - statsmodels==0.12.1
    - sympy==1.7.1
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - torch==1.7.1
    - tqdm==4.56.0
    - typer==0.3.2
    - typing-extensions==3.7.4.3
    - uproot==4.0.0
    - uproot3==3.14.2
    - uproot3-methods==0.10.0
    - urllib3==1.26.2
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xgboost==1.3.3
